In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv('diabetes_prediction_dataset.csv')
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [3]:
df.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [4]:
df.tail()

gender   age  hypertension  heart_disease smoking_history    bmi  \
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0

In [5]:
#random_values = np.random.randint(0, 2, df['smoking_history'].value_counts()['No Info'])

# Replacing 'No Info' with random 0 or 1
#df.loc[df['smoking_history'] == 'No Info', 'smoking_history'] = random_values

# Converting other values
#df['smoking_history'] = df['smoking_history'].replace({'never': 0, 'current': 1})

#print(df)

In [6]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [7]:
df['smoking_history'].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [8]:
# Converting other values
df['smoking_history'] = df['smoking_history'].replace({'never': 0, 'current': 1})
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1               0  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0               0  27.32   
3      Female  36.0             0              0               1  23.45   
4        Male  76.0             1              1               1  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0               0  35.42   
99999  Female  57.0             0              0               1  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [9]:
# Generating random values of 0 or 1 for 'No Info', 'former', 'ever', 'not current'
categories_to_randomize = ['No Info', 'former', 'ever', 'not current']
random_values = np.random.randint(0, 2, df['smoking_history'].isin(categories_to_randomize).sum())

# Replacing the specified categories with random 0 or 1
df.loc[df['smoking_history'].isin(categories_to_randomize), 'smoking_history'] = random_values

In [10]:
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1               0  25.19   
1      Female  54.0             0              0               0  27.32   
2        Male  28.0             0              0               0  27.32   
3      Female  36.0             0              0               1  23.45   
4        Male  76.0             1              1               1  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0               0  27.32   
99996  Female   2.0             0              0               1  17.37   
99997    Male  66.0             0              0               1  27.83   
99998  Female  24.0             0              0               0  35.42   
99999  Female  57.0             0              0               1  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [11]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [12]:
y=df['diabetes']
x=df.drop(columns=['diabetes'],axis=1)
x

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1               0  25.19   
1      Female  54.0             0              0               0  27.32   
2        Male  28.0             0              0               0  27.32   
3      Female  36.0             0              0               1  23.45   
4        Male  76.0             1              1               1  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0               0  27.32   
99996  Female   2.0             0              0               1  17.37   
99997    Male  66.0             0              0               1  27.83   
99998  Female  24.0             0              0               0  35.42   
99999  Female  57.0             0              0               1  22.43   

       HbA1c_level  blood_glucose_level  
0              6.6                  140  
1              6.6                   80  
2              5.7                  158  
3              5.0                  155  
4              4.8                  155  
...            ...                  ...  
99995          6.2                   90  
99996          6.5                  100  
99997          5.7                  155  
99998          4.0                  100  
99999          6.6                   90  

[100000 rows x 8 columns]

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le=LabelEncoder()
x['gender']=le.fit_transform(x['gender'])
x

gender   age  hypertension  heart_disease smoking_history    bmi  \
0           0  80.0             0              1               0  25.19   
1           0  54.0             0              0               0  27.32   
2           1  28.0             0              0               0  27.32   
3           0  36.0             0              0               1  23.45   
4           1  76.0             1              1               1  20.14   
...       ...   ...           ...            ...             ...    ...   
99995       0  80.0             0              0               0  27.32   
99996       0   2.0             0              0               1  17.37   
99997       1  66.0             0              0               1  27.83   
99998       0  24.0             0              0               0  35.42   
99999       0  57.0             0              0               1  22.43   

       HbA1c_level  blood_glucose_level  
0              6.6                  140  
1              6.6                   80  
2              5.7                  158  
3              5.0                  155  
4              4.8                  155  
...            ...                  ...  
99995          6.2                   90  
99996          6.5                  100  
99997          5.7                  155  
99998          4.0                  100  
99999          6.6                   90  

[100000 rows x 8 columns]

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc=StandardScaler()

In [19]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [20]:
x_train

array([[-0.84077439,  1.68927554, -0.28445412, ..., -0.00383155,
        -0.67622209,  0.51531068],
       [-0.84077439, -1.8302007 , -0.28445412, ..., -1.69896895,
         0.25584604, -1.17972675],
       [-0.84077439, -0.44158798, -0.28445412, ..., -0.00983203,
         1.00150055,  0.51531068],
       ...,
       [ 1.18770178,  1.06777368, -0.28445412, ...,  2.0828376 ,
         3.23846406,  0.17139004],
       [-0.84077439, -0.21962303, -0.28445412, ...,  0.42520323,
         0.25584604, -1.17972675],
       [-0.84077439,  0.44627182, -0.28445412, ..., -0.00383155,
        -0.95584252,  0.49074492]])

In [21]:
x_test

array([[-0.84168246,  0.45600059, -0.28440522, ...,  0.00868541,
        -0.68718791,  0.04570476],
       [ 1.1861423 ,  0.63382389, -0.28440522, ...,  0.00868541,
        -0.68718791, -0.93685869],
       [-0.84168246, -0.87767417, -0.28440522, ...,  1.50701082,
         1.00221838, -1.30531998],
       ...,
       [ 1.1861423 , -0.69985087, -0.28440522, ...,  0.00868541,
         0.62679476,  0.16852519],
       [-0.84168246,  0.18926564, -0.28440522, ..., -0.25626237,
         0.15751524,  1.51954993],
       [-0.84168246, -0.96658582, -0.28440522, ..., -0.85011085,
         0.15751524,  0.41416605]])

In [22]:
from tensorflow.keras.models import Sequential
from keras.layers import Dense

In [23]:
model=Sequential()

In [24]:
x.shape

(100000, 8)

In [25]:
model.add(Dense(units=20,activation='relu',kernel_initializer='random_uniform'))
model.add(Dense(units=40,activation='relu',kernel_initializer='random_uniform'))
model.add(Dense(units=45,activation='relu',kernel_initializer='random_uniform'))
model.add(Dense(units=40,activation='relu',kernel_initializer='random_uniform'))
model.add(Dense(units=45,activation='relu',kernel_initializer='random_uniform'))
model.add(Dense(units=1,activation='sigmoid',kernel_initializer='random_uniform'))


In [26]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [27]:
x_train.shape

(70000, 8)

In [53]:
model.fit(x_train,y_train,batch_size=32,epochs=40)

Epoch 1/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9719 - loss: 0.0814
Epoch 2/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9723 - loss: 0.0793
Epoch 3/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.9717 - loss: 0.0805
Epoch 4/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9724 - loss: 0.0804
Epoch 5/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9725 - loss: 0.0794
Epoch 6/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9723 - loss: 0.0808
Epoch 7/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9730 - loss: 0.0782
Epoch 8/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9728 - loss: 0.0784
Epoch 9/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9728 - loss: 0.0792
Epoch 10/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9733 - loss: 0.0792
Epoch 11/40
2188/2188 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9718 - loss: 0.0805
Epoch 12/40
2188/2188 ━━━━━━━

In [54]:
y_pred=model.predict(x_test)

938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step


In [55]:
y_pred

array([[0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       ...,
       [1.8008087e-02],
       [3.5320576e-03],
       [3.6974754e-10]], dtype=float32)

In [56]:
from sklearn.metrics import accuracy_score

In [57]:
y_pred_class = (y_pred > 0.5).astype(int)  # For binary classification
accuracy = accuracy_score(y_pred_class, y_test)
print(accuracy)

0.9716


In [34]:
#app=np.array(sc.transform(le.transform([['Female',80.0,0,1,0,25.19,6.6,140]])))
#app

array([[  0.  ,  80.  ,   0.  ,   1.  ,   0.  ,  25.19,   6.6 , 140.  ]])

In [42]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Sample input
sample_input = ['Female', 44.0, 0, 0, 0, 19.31, 6.5, 200]

# Initialize LabelEncoder and StandardScaler
le = LabelEncoder()
sc = StandardScaler()

# Fit the LabelEncoder on the training data (example categories: 'Female' and 'Male')
le.fit(['Female', 'Male'])

# Assume this is your training data for the numerical features
numerical_training_data = np.array([
    [80.0, 0, 1, 0, 25.19, 6.6, 140],
    
    # Add more training data here
])

# Fit the StandardScaler on the training numerical data
sc.fit(numerical_training_data)

# Now, transform the sample input
encoded_categorical = le.transform([sample_input[0]])  # Encoded categorical feature

# Transform the numerical features
numerical_features = np.array(sample_input[1:]).reshape(1, -1)
scaled_numerical = sc.transform(numerical_features)  # Scaled numerical features

# Combine the transformed categorical and scaled numerical features
transformed_input = np.concatenate([encoded_categorical, scaled_numerical.flatten()])

# Convert to a 2D array (as input for a model)
transformed_input = transformed_input.reshape(1, -1)

# Output the transformed array
print(transformed_input)


[[  0.   -36.     0.    -1.     0.    -5.88  -0.1   60.  ]]


In [43]:
transformed_input

array([[  0.  , -36.  ,   0.  ,  -1.  ,   0.  ,  -5.88,  -0.1 ,  60.  ]])

In [44]:
yp=model.predict(transformed_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


In [45]:
yp

array([[1.]], dtype=float32)

In [62]:
model.save("dia.h5")

In [63]:
import joblib
joblib.dump(le,"dia_le")

['dia_le']

In [64]:
import pickle
pickle.dump(sc,open("dia_scaler.pkl",'wb'))